---
layout: post
title: Java语言基础(SE)-第五节 异常
category: Java后端开发
tags: Java后端开发
description: Java后端开发
--- 

## 异常（Exception）
1. 开发中的错误
    1. 在开发 Java 程序的过程中，会遇到各种各样的错误
        1. 语法错误
            1. 会导致编译失败，程序无法正常运行
        2. 逻辑错误
            1. 比如需要执行加法操作时，不小心写成了减法操作
        3. 运行时错误
            1. 在程序运行过程中产生的意外，会导致程序终止运行
            2. 在 Java 中也叫做异常
2. 如何防止程序因为抛出异常导致终止运行？
    1. 可以通过 try-catch 来捕捉处理异常

#### 异常的种类
1. 所有的异常最终都继承自 java.lang.Throwable
        
    ```
                            Object
                            Throwable 
                    Exception       Error
      RuntimeException      ...     ...
              ...
    ```
2. 检查型异常（Checked Exception）
    1. 这类异常一般难以避免，编译器会进行检查
        1. 如果开发者没有处理这类异常，编译器将会报错
    2. 哪些异常是检查型异常？
        1. 除 Error、RuntimeException以及其子类，以外的异常
3. 非检查型异常（Unchecked Exception）
    1. 这类异常一般可以避免，编译器不会进行检查
        1. 如果开发者没有处理这类异常，编译器将不会报错
    2. 哪些异常是非检查型异常？
        1. Error、RuntimeException以及其子类
4. 常见的检查型异常
    
    ```
    //java.io.FileNotFoundException 文件不存在
    FileOutputStream fos = new FileOutputStream("F://xxx.txt");
    //反射
    //java.lang.ClassNotFoundException,不存在这个类
    Class cls = Class.forName("Dog");
    //java.lang.InstantiationException,没有无参的构造函数
    //java.lang.IllegalAccessException,没有权限访问构造函数
    Dog dog = (Dog) cls.newInstance();
    ```
5. 常见的非检查型异常
    1. Error
        
        ```
        //java.lang.OutOfMemoryError,内存不够用
        for (int i = 0; i < 200; i++) {
            long[] a = new long[1000000000];
        }
        ```
    2. RuntimeException
        
        ```
        //java.lang.NullPointerException,使用了空指针
        StringBuilder s = null;
        s.append("abc");
        
        //java.lang.NumberFormatException数字的格式不对
        Integer i = new Integer("abc");
        
        int[] array = {11,22,33};
        //java.lang.ArrayIndexOutOfBoundsException,数组索引越界
        array[4] = 44；
        
        Object obj = "123.4";
        //java.lang.ClassCastException:类型不匹配
        Double d = (Double)obj;
        ```

### 异常处理
1. 程序产生了异常，一般称之为：抛出了异常
    1. 如果没有主动去处理它，会导致程序终止运行
2. 异常处理有2种方法
    1. try-catch: 捕获异常
    2. throws： 将异常往上抛

#### try-catch
1. 示例代码
    
    ```
    try {
    代码1
    代码2 （可能会抛出异常） 
    代码3
    	
    } catch (异常A e) {
    	//当抛出【异常A】类型的异常时，会进入这个代码块
    }catch (异常B e) {
    	//当没有抛出【异常A】类型 
    	//但抛出【异常B】类型的异常时，会进入这个代码块
    }catch (异常C e) {
    	//当没有抛出【异常A】、【异常B】类型 
    	//但抛出【异常C】类型的异常时，会进入这个代码块
    }
    代码4
    ```
    
    1. 如果【代码2】没有抛出异常
        1. 【代码1、3】都会被执行
        2. 所有的 catch 都不会被执行
        3. 【代码4】会被执行
    2. 如果【代码2】抛出异常
        1. 【代码1】会被执行、【代码3】不会被执行
        2. 会选择匹配的 catch 来执行代码
        3. 【代码4】会被执行
    3. 父类型的异常必须写在子类型的后面
        1. 【异常A】不可以是【异常B、C】的父类型
        2. 【异常B】不可以是【异常C】的父类型
2. 异常对象的常用方法
    
    ```
    try {
        Integer i = new Integer("abc");
    } catch (NumberFormatException e) {
        //异常描述
        System.out.println(e.getMessage());
        //异常名称 异常描述
        System.out.println(e);
        //打印堆栈信息
        e.printStackTrace();
    }
    ```
3. 一个 catch 捕获多种类型的异常
    1. 从 Java 7 开始，单个 catch 可以捕获多种类型的异常
    2. 如果并列的几个异常类型之间存在父子关系，保留父类型即可
    3. 这里的变量 e 是隐式 final 的,就是e不能再次赋值了
    
    ```
    try {
    } catch (异常A | 异常B | 异常C  e) {
        //当抛出【异常A】或【异常B】或【异常C】类型的异常时，会进入这个代码块
    }
    ```
    
#### finally
1. try 或 catch 正常执行完毕后，一定会执行 finally 中的代码
    1. finally 可以和 try-catch 搭配使用，也可以只和 try 搭配使用
    2. 经常会在 finally 中编写一些关闭、释放资源的代码（比如关闭文件）

    ```
    try {
    } catch (异常e) {
    }finally {
    }
    try {
    }finally {
    }
    ```
2. 举例：
    
    ```
    PrintWriter  out = null;
    try {
        out = new PrintWriter("F:/zh.txt");
        //向文件中写入内容
        out.print("My name is ZH");
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } finally {
        if (out != null) {
            //关闭文件
            out.close();
        }
    }
    ```
3. finally 细节
    1. 如果在执行 try 或 catch 时，JVM 退出或者当前线程被中断、杀死
        1. finally 可能不会执行
    2. 如果 try 或 catch 中使用了 return、break、 continue 等提前结束语句
        1. finally 会在 return、break、continue 之前执行
    3. 下面代码的打印结果是什么？
        
        ```
        for (int i = 1; i <= 3; i++) {
        try {
            System.out.println(i + "_try_1");
            if (i== 2) continue;
                System.out.println(i + "_try_2");
            } finally {
                System.out.println(i + "_finally");
            } 
        }
        ```
        
        1. 上面是continue，则打印结果
            
            ```
            1_try_1
            1_try_2
            1_finally
            2_try_1
            2_finally
            3_try_1
            3_try_2
            3_finally
            ```
        2. 如果是break
            
            ```
            1_try_1
            1_try_2 
            1_finally 
            2_try_1 
            2_finally
            ```
    4. 代码举例：
        
        ```
        static int get() {
            try {
                new Integer("abc");
                System.out.println(1);
                return 2;
            } catch (Exception e) {
                System.out.println(3);
                //return之前要先去调用finally！！！
                return 4;
            } finally {
                System.out.println(5);
            }
        }
        
        public static void main(String[] args) { 
            System.out.println(get());
        }
        //打印结果： 3 5 4
        ```
        
    
        


